### ISSUE TITLE
Unstyled text in direct messages list

### ISSUE THREAD

**Issue by extesy** [caiceA/slack-black-theme#97]
**Describe the bug**
When looking up a direct contact, the highlighted block has light-gray on light-gray color.

**To Reproduce**
1. Go to 'Direct Messages'
2. Start typing some name
3. Highlight one of them with a cursor

**Expected behavior**
Background should be dark, not light-gray.

**Screenshots**
![image](https://user-images.githubusercontent.com/65872/62963812-8be13300-bdb6-11e9-801b-f503ba741e71.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6

**Comment by rahuliyer95** [comment]
I think the selector is `div.p-dm_browser_modal__list_row--active.c-base_list_entity.c-base_list_entity--medium`

**Comment by caiceA** [comment]
@extesy thanks for reporting an issue. 
I have fixed this

**Comment by extesy** [comment]
@caiceA Thanks for the fix! How does the re-install work? Does the shell script replace the modified code or just appends another copy of it to the bundle?

**Comment by caiceA** [comment]
@extesy you don't need to do anything on such issue  just restart Slack

**Comment by rahuliyer95** [comment]
I am sorry but I am still facing this issue. I am using the `slack-dark-mode.css` from master
<img width="907" alt="Screen Shot 2019-08-14 at 2 37 39 PM" src="https://user-images.githubusercontent.com/4255590/63059512-7e09db80-bea4-11e9-91f6-7afb607579b4.png">

**Comment by caiceA** [comment]
don't use that css 
use this path https://raw.githubusercontent.com/caiceA/slack-raw/master/slack-4
